export interface Ticket {
    id?: number;
    ticket_no?: string; // Generated by DB (e.g., T-8531)
    customer_id?: number;
    email?: string;
    mobile?: string;
    service_address?: string;
    priority: 'Low' | 'Medium' | 'High' | 'Urgent';
    service_type: string;
    assigned_technician_id?: number | null;
    scheduled_date?: string | null;
    equipment_type?: string;
    equipment_model?: string;
    issue_description?: string;
    status?: {
        id: number,
        name: string
    };
    status_id?: number;
    created_by?: number;
    createdAt?: string;
    updatedAt?: string;
    // Nested Objects from Sequelize "include"
    customer?: {
        id: number;
        name: string;
        mobile: string;
        email: string;
        address: string;
    };
    assignedTechnician?: {
        id: number;
        name: string;
        mobile: string;
    };
    // Optional joined data for the table view
    customer_name?: string;
    technician_name?: string;
}

export interface TicketResponse {
    success: boolean;
    data: {
        tickets: Ticket[];
        pagination: {
            total: number;
            totalPages: number;
            limit: number;
            currentPage: number;
        };
    };
}

export interface TicketStatusHistory {
    id: number;
    ticket_id: number | null;
    status_id: number; // The status it was changed TO
    changed_by: number;
    changed_at: string;
    user?: { // If your backend includes the joined user
        name: string;
    };
}

export interface TicketStatusHistoryResponse {
    success: boolean;
    data: TicketStatusHistory[];
};
