export interface Ticket {
    id?: number;
    ticket_no?: string; // Generated by DB (e.g., T-8531)
    customer_id?: number;
    email?:string;
    mobile?:string;
    service_address?: string;
    priority: 'Low' | 'Medium' | 'High' | 'Urgent';
    service_type: string;
    assigned_technician_id?: number | null;
    scheduled_date?: string | null;
    equipment_type?: string;
    equipment_model?: string;
    issue_description?: string;
    status?: string;
    created_by?: number;
    createdAt?: string;
    updatedAt?: string;

    // Optional joined data for the table view
    customer_name?: string;
    technician_name?: string;
}

export interface TicketResponse {
    success: boolean;
    data: {
        tickets: Ticket[];
        pagination: {
            total: number;
            totalPages: number;
            limit: number;
            currentPage: number;
        };
    };
}